global:
  smtp_smarthost: '${ALERT_SMTP_HOST}'
  smtp_from: '${ALERT_SMTP_FROM}'
  smtp_auth_username: '${ALERT_SMTP_USER}'
  smtp_auth_password: '${ALERT_SMTP_PASSWORD}'
  smtp_require_tls: true

route:
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: '${ALERT_SMTP_TO}'
        from: 'appatino@espe.edu.ec'
        send_resolved: true
        headers:
            Subject: 'Prometheus Alert: {{ .CommonLabels.alertname }}'
            To: monitoring-to@example.com
        html: |
          <br><hr><br>TEST ALERTMANAGER
          {{ range .Alerts }}
            <p>
              <strong>{{ .Annotations.summary }}</strong><br>
              {{ .Annotations.description }}
            </p>
            <hr>
          {{ end }}
