version: '3.8'

services:
  grafana:
    image: grafana/grafana:11.3.1
    ports:
      - "${GRAFANA_PORT_EXTERNAL}:${GRAFANA_PORT_INTERNAL}"
    environment:
      GF_SECURITY_ADMIN_USER: "${GRAFANA_USER}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_PASSWORD}"
    volumes:
      - grafana_storage:/var/lib/grafana
      - shared_configs:/app/docker/integraciones_security_monitoring
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - shared_configs:/app/docker/integraciones_security_monitoring
      - shared_configs_prometheus:/etc/prometheus
    ports:
      - "${PROMETHEUS_PORT_EXTERNAL}:${PROMETHEUS_PORT_INTERNAL}"
    networks:
      - monitoring
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - shared_configs:/app/docker/integraciones_security_monitoring
      - shared_configs_alertmanager:/etc/alertmanager
    ports:
      - "${ALERTMANAGER_PORT_EXTERNAL}:${ALERTMANAGER_PORT_INTERNAL}"
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    networks:
      - monitoring

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}?sslmode=disable"
    ports:
      - "${EXPORT_POSTGRES_PORT_EXTERNAL}:${EXPORT_POSTGRES_PORT_INTERNAL}"
    networks:
      - monitoring

  mongo-exporter:
    image: ssheehy/mongodb-exporter:latest
    environment:
      MONGODB_URI: "${MONGODB_URI}"
    ports:
      - "${EXPORT_MONGO_PORT_EXTERNAL}:${EXPORT_MONGO_PORT_INTERNAL}"
    networks:
      - monitoring

  mariadb-exporter:
    image: prom/mysqld-exporter
    command:
      - --config.my-cnf=/cfg/.my.cnf
    volumes:
      - shared_configs:/app/docker/integraciones_security_monitoring
      - shared_configs_mariadb:/cfg
    ports:
      - "${EXPORT_MARIADB_PORT_EXTERNAL}:${EXPORT_MARIADB_PORT_INTERNAL}"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_storage:
  shared_configs:
    external: true
  shared_configs_prometheus:
    driver: local
  shared_configs_alertmanager:
    driver: local
  shared_configs_mariadb:
    driver: local
