global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:${PROMETHEUS_PORT_INTERNAL}']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:${EXPORT_POSTGRES_PORT_INTERNAL}']

  - job_name: 'mongo'
    static_configs:
      - targets: ['mongo-exporter:${EXPORT_MONGO_PORT_INTERNAL}']